name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://golang:1.15.7-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build
        run: |
          go get -d ./...
          GOOS=linux GOARCH=amd64 go build -o build/escher-proxy-linux-amd64 proxy.go
          GOOS=linux GOARCH=arm64 go build -o build/escher-proxy-linux-arm64 proxy.go
          GOOS=windows go build -o build/escher-proxy-windows-amd64.exe proxy.go
          GOOS=darwin go build -o build/escher-proxy-darwin-amd64 proxy.go
      - name: Create artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: build/