name: CI

on: push

jobs:
  build:
    if: endsWith(github.ref, 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.7'
      - name: Run build
        run: |
          go get -d ./...
          GOOS=linux GOARCH=amd64 go build -o build/escher-proxy-linux-amd64 proxy.go
          GOOS=linux GOARCH=arm64 go build -o build/escher-proxy-linux-arm64 proxy.go
          GOOS=windows go build -o build/escher-proxy-windows-amd64.exe proxy.go
          GOOS=darwin go build -o build/escher-proxy-darwin-amd64 proxy.go
      - name: Create artifacts
        uses: actions/upload-artifact@v2
        with:
          name: escher-proxy-binaries
          path: build/

  release:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries artifact
        uses: actions/download-artifact@v2
        with:
          name: escher-proxy-binaries
      - name: Uploaded binaries as release assets
        run: |
          set -x
          tag_name="${GITHUB_REF##*/}"
          assets=()
          for binary in ./build/*; do
            cp "$binary" "${binary}-${tag_name}"
            assets+=("-a" "${binary}-${tag_name}"")
          done
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}